# Generated by Django 3.2.4 on 2021-07-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='footage',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='script',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
