# Generated by Django 3.2.4 on 2021-07-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210716_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Finished Sketch'),
        ),
        migrations.AlterField(
            model_name='video',
            name='footage',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Footage'),
        ),
        migrations.AlterField(
            model_name='video',
            name='script',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Script'),
        ),
    ]
