# Generated by Django 3.2.4 on 2021-08-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210817_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketchfileupload',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='sketchfileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='sketchfileupload',
            name='type',
            field=models.CharField(default='FOOTAGE', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
