# Generated by Django 3.2.4 on 2021-08-17 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210817_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchfileupload',
            name='sketch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sketch'),
        ),
    ]
